### PR TITLE
Add PPN photolysis rate and cross sections

### PR DESCRIPTION
**Pull request by bexhorner**
### Name and Institution (Required)

Name: Bex Horner, @eamarais
Institution: University College London (UCL)

### Describe the update

This update adds PPN photolysis rates and cross-sections derived from those of PAN as outlined in Horner et al. (2024). 

### Expected changes

NO2 concentrations will increase in the upper troposphere by ~30-60 pptv where PPN is abundant and thermally stable. 

This also requires updating the GEOS-Chem Science Codebase repository outlined in [PR #2371](https://github.com/geoschem/geos-chem/pull/2371). 

### Reference(s)

Horner et al. 2024. "Vertical profiles of global tropospheric nitrogen dioxide (NO2) obtained via cloud-slicing" (https://doi.org/10.5194/egusphere-2024-1541)

### Related Github Issues and PRs

GEOS-Chem Science Codebase [PR #2371](https://github.com/geoschem/geos-chem/pull/2371)

### CODE REVIEW

**Comment by lizziel** [comment]
Hi @bexhorner, I think there may be some confusion about the usage of the tables directory in Cloud-J. The files there are for example only, for usage within the Cloud-J standalone. They are not used by GEOS-Chem. The data files used by GEOS-Chem are stored externally in ExtData along with emissions inputs etc. The path to the files used is specified in GEOS-Chem configuration file `geoschem_config.yml`. We can definitely add this update to the example dat-files, but I want to make sure this is what you intend.

**Comment by lizziel** [comment]
I should add that we can create new files in ExtData for use with your GEOS-chem updates.

**Comment by eamarais** [comment]
@lizziel and @bexhorner, this should really be part of [this pull request](url) rather than the CLOUD-J standalone to implement Bex's PPN photolysis updates in the standard code. This updates the KPP fullchem.eqn file and input files for photolysis.

**Comment by lizziel** [comment]
Thanks for clarifying @eamarais! I will close this PR. I added a comment to https://github.com/geoschem/geos-chem/pull/2371 that we will need to make a new Cloud-J input data directory for that update.

**Pull request closed without merging**
